### ISSUE TITLE
Not working with composer 2 anymore.

### ISSUE THREAD

**Issue by dkern** [helhum/env-ts#5]
Like the title said, it's not working with Composer v2.

**Comment by helhum** [comment]
Thanks. What TYPO3 version are you using in combination with this package?

**Comment by dkern** [comment]
Should be v9 and v10.

**Comment by dkern** [comment]
I have the same problem again. On new servers there will normally composer 2 be installed by default. But because of `env-ts`, we have to downgrade them to composer 1. I don't know exactly what you use the `composer-plugin-api` for, but do you think we could easily change this to `^1||^2` ?

**Comment by helhum** [comment]
Might be. The package itself is deprecated though. There are better solution to solve the problem for TYPO3 9 and 10. 

But I'll merge a pull request fixing the issue if you create one and release one last version.

**Comment by dkern** [comment]
To be honest, I've never noticed that this is deprecated. Then ignore my request please. ;)

Maybe add a notice to the readme.

**Comment by helhum** [comment]
Oh, OK, I assumed you would have seen the deprecation message on *each* Composer install, as the package is marked as [abandoned](https://packagist.org/packages/helhum/env-ts)

I'll additionally add a remark on the README like suggested.
